FROM quay.io/modh/cuda-notebooks@sha256:d8295bcf45a6a522f78c07dc62634a7775fc434621973bd81db243a5a63a1ffa
WORKDIR /opt/app-root/src
RUN git clone https://github.com/eformat/auto-evaluator
RUN pip install --no-cache-dir -r auto-evaluator/api/requirements.txt
EXPOSE 8000
ENTRYPOINT python api/evaluator_app.py
